# Generated by Django 2.0.3 on 2019-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190109_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Event:'),
        ),
    ]
